### ISSUE TITLE
url后面有内容，刷新页面报错

### ISSUE THREAD

**Issue by kanbang** [zy7y/mini-rbac#10]
非常干净清爽的框架！
![fastapi](https://github.com/zy7y/mini-rbac/assets/4978439/f3fbb446-7480-4fe5-831f-be331e05710f)

url后面有内容，刷新页面报错

**Comment by zy7y** [comment]
> 非常干净清爽的框架！ ![fastapi](https://user-images.githubusercontent.com/4978439/239795336-f3fbb446-7480-4fe5-831f-be331e05710f.png)
> 
> url后面有内容，刷新页面报错

参考文档分别运行前端和后端 访问前端地址就行了 ，如果非要直接访问后端挂载的前端文件应该是要在端口后面/static
