### ISSUE TITLE
前端添加了页面，用户也给了页面权限，但是运行起来之后页面看不到页面

### ISSUE THREAD

**Issue by 1353626525** [zy7y/mini-rbac#12]

**Comment by zy7y** [comment]
[具体添加方式](https://www.bilibili.com/video/BV1mP411H7PL/?spm_id_from=333.999.0.0&vd_source=f824feef5305252d9a349520313fd4db)

**Comment by zy7y** [comment]
> [具体添加方式](https://www.bilibili.com/video/BV1mP411H7PL/?spm_id_from=333.999.0.0&vd_source=f824feef5305252d9a349520313fd4db)

<img width="1440" alt="image" src="https://github.com/zy7y/mini-rbac/assets/67154681/18e920d4-f05a-4d44-a9fc-13795a93f859">
