### ISSUE TITLE
想请教一下sys_menu表的问题

### ISSUE THREAD

**Issue by yuki1sntSnow** [zy7y/mini-rbac#7]
sys_menu 中 component 和 identifier 列的具体作用。

**Comment by yuki1sntSnow** [comment]
前端路由，全部解耦去掉了。

**Comment by zy7y** [comment]
> sys_menu 中 component 和 identifier 列的具体作用。

component，指的是前端组件在views/main下面的具体文件路径，
identifiter，指的是按钮权限标识，例如用户添加user:add，具体可以结合演示站点，源码查看

**Comment by zy7y** [comment]
> sys_menu 中 component 和 identifier 列的具体作用。

component，指的是前端组件在views/main下面的具体文件路径，
identifiter，指的是按钮权限标识，例如用户添加user:add，具体可以结合演示站点，源码查看
