### ISSUE TITLE
新建接口无权访问

### ISSUE THREAD

**Issue by yangaphero** [zy7y/mini-rbac#9]
在route中新建接口，docs中可以看到路由生成，但是访问时候 check_permissions出现无权访问。

 has_permissions(active_rid)查询数据库sys_role_menu中没有新添加的接口。

github中是最新新的吗？

**Comment by zy7y** [comment]
route 中新建接口，对应用户角色你得给权限才行啊

**Comment by zy7y** [comment]
> 在route中新建接口，docs中可以看到路由生成，但是访问时候 check_permissions出现无权访问。
> 
> has_permissions(active_rid)查询数据库sys_role_menu中没有新添加的接口。
> 
> github中是最新新的吗？

route 中新建接口，对应用户角色你得给权限才行啊
